groups:
  - name: ai-workflow-playbook-alerts
    rules:
      # 애플리케이션 다운 알림
      - alert: ApplicationDown
        expr: up{job="ai-workflow-playbook"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "AI Workflow Playbook application is down"
          description: "The AI Workflow Playbook application has been down for more than 1 minute."

      # 높은 응답 시간 알림
      - alert: HighResponseTime
        expr: ai_workflow_requests_duration_seconds{quantile="0.95"} > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for more than 2 minutes."

      # 높은 에러율 알림
      - alert: HighErrorRate
        expr: rate(ai_workflow_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second for more than 2 minutes."

      # 메모리 사용량 높음
      - alert: HighMemoryUsage
        expr: ai_workflow_memory_usage_bytes / (1024*1024*1024) > 1.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}GB for more than 5 minutes."

      # 디스크 공간 부족
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Available disk space is {{ $value }}% for more than 5 minutes."

  - name: infrastructure-alerts
    rules:
      # Redis 연결 실패
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis has been down for more than 1 minute."

      # Nginx 다운
      - alert: NginxDown
        expr: up{job="nginx"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Nginx is down"
          description: "Nginx has been down for more than 1 minute."

      # 높은 CPU 사용률
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}% for more than 5 minutes."

  - name: business-metrics-alerts
    rules:
      # MVP 생성 실패율 높음
      - alert: HighMVPFailureRate
        expr: rate(ai_workflow_mvp_failures_total[10m]) / rate(ai_workflow_mvp_attempts_total[10m]) > 0.2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High MVP generation failure rate"
          description: "MVP generation failure rate is {{ $value }}% for more than 5 minutes."

      # 컴포넌트 생성 지연
      - alert: SlowComponentGeneration
        expr: ai_workflow_component_generation_duration_seconds{quantile="0.95"} > 30
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Slow component generation"
          description: "95th percentile component generation time is {{ $value }}s for more than 3 minutes."